export type CarType = {
  id: string,
  name: string,
  group: string,
  price: number,
  combustible: string,
  maletas: number,
  puertas: number,
  caja: string,
  plazas: number,
  image: string
};

export const Cars = [
  {
    id: "sdfi32",
    name: "Peugeot 208 Like",
    group: "B",
    price: 10000.00,
    combustible: "Nafta",
    maletas: 2,
    puertas: 5,
    caja: "Manual",
    plazas: 5,
    image: "/images2/peugeot208.webp"
  },
  {
    id: "sdfi31",
    name: "Toyota Etios",
    group: "B",
    price: 47235.50,
    combustible: "Nafta",
    maletas: 2,
    puertas: 5,
    caja: "Manual",
    plazas: 5,
    image: "/images2/toyotaetios.webp"
  },
  {
    id: "s4dfi3",
    name: "Nissaan Versa",
    group: "H",
    price: 74260.50,
    combustible: "Nafta",
    maletas: 4,
    puertas: 4,
    caja: "Automática",
    plazas: 5,
    image: "/images2/nissanversa.webp"
  },
  {
    id: "sdf6i3",
    name: "Toyota Hilux 4x4",
    group: "X",
    price: 185532.50,
    combustible: "Diesel",
    maletas: 6,
    puertas: 4,
    caja: "Manual",
    plazas: 5,
    image: "/images2/toyotahilux.webp"
  },
  {
    id: "sdyfi3",
    name: "Peugeot 208 Like",
    group: "B",
    price: 47235.50,
    combustible: "Nafta",
    maletas: 2,
    puertas: 5,
    caja: "Manual",
    plazas: 5,
    image: "/images2/peugeot208.webp"
  },
  {
    id: "sdfli3",
    name: "Toyota Etios",
    group: "B",
    price: 47235.50,
    combustible: "Nafta",
    maletas: 2,
    puertas: 5,
    caja: "Manual",
    plazas: 5,
    image: "/images2/toyotaetios.webp"
  },
  {
    id: "sdfi3x",
    name: "Nissaan Versa",
    group: "H",
    price: 74260.50,
    combustible: "Nafta",
    maletas: 4,
    puertas: 4,
    caja: "Automática",
    plazas: 5,
    image: "/images2/nissanversa.webp"
  },
  {
    id: "sdxfi3",
    name: "Toyota Hilux 4x4",
    group: "X",
    price: 185532.50,
    combustible: "Diesel",
    maletas: 6,
    puertas: 4,
    caja: "Manual",
    plazas: 5,
    image: "/images2/toyotahilux.webp"
  },
  {
    id: "xsdfi3",
    name: "Peugeot 208 Like",
    group: "B",
    price: 47235.50,
    combustible: "Nafta",
    maletas: 2,
    puertas: 5,
    caja: "Manual",
    plazas: 5,
    image: "/images2/peugeot208.webp"
  },
  {
    id: "sdafi3",
    name: "Toyota Etios",
    group: "B",
    price: 47235.50,
    combustible: "Nafta",
    maletas: 2,
    puertas: 5,
    caja: "Manual",
    plazas: 5,
    image: "/images2/toyotaetios.webp"
  },
  {
    id: "sdfia3",
    name: "Nissaan Versa",
    group: "H",
    price: 74260.50,
    combustible: "Nafta",
    maletas: 4,
    puertas: 4,
    caja: "Automática",
    plazas: 5,
    image: "/images2/nissanversa.webp"
  },
  {
    id: "asdfi3",
    name: "Toyota Hilux 4x4",
    group: "X",
    price: 185532.50,
    combustible: "Diesel",
    maletas: 6,
    puertas: 4,
    caja: "Manual",
    plazas: 5,
    image: "/images2/toyotahilux.webp"
  },
]