export const statesCodes = [
  {value:"C",label:"Ciudad Autónoma de Buenos Aires"},
  {value:"B",label:"Buenos Aires"},
  {value:"K",label:"Catamarca"},
  {value:"H",label:"Chaco"},
  {value:"U",label:"Chubut"},
  {value:"X",label:"Córdoba"},
  {value:"E",label:"Entre Ríos"},
  {value:"P",label:"Formosa"},
  {value:"Y",label:"Jujuy"},
  {value:"L",label:"La Pampa"},
  {value:"F",label:"La Rioja"},
  {value:"M",label:"Mendoza"},
  {value:"N",label:"Misiones"},
  {value:"Q",label:"Neuquén"},
  {value:"R",label:"Río Negro"},
  {value:"A",label:"Salta"},
  {value:"J",label:"San Juan"},
  {value:"D",label:"San Luis"},
  {value:"Z",label:"Santa Cruz"},
  {value:"S",label:"Santa Fe"},
  {value:"G",label:"Santiago del Estero"},
  {value:"V",label:"Tierra del Fuego"},
  {value:"T",label:"Tucumán"},
]